# Setup

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
import sys
sys.path.append("../")

from utils.seed_all import seed_all

DEFAULT_SEED = 10
seed_all(DEFAULT_SEED)

In [3]:
def plot_img_loss(img_loss, min=None, max=None, targets=[]):
    plt.figure(figsize=(10, 8))  # Adjust size as needed
    plt.imshow(img_loss, cmap='gray_r', aspect='auto', interpolation='nearest', vmin=min, vmax=max)
    plt.colorbar(label='Normalized Loss')

    # Draw horizontal lines for rows with label == 1
    for i, lbl in enumerate(targets):
        if lbl != 'Normal':
            plt.axhline(i - 0.5, color='red', linewidth=1.5, alpha=0.1)  # top edge
            plt.axhline(i + 0.5, color='red', linewidth=1.5, alpha=0.1)  # bottom edge

    plt.xlabel("Byte Index")
    plt.ylabel("Window Index")
    plt.title("Mean Image Loss Map")
    plt.tight_layout()
    plt.show()
    plt.close()

In [10]:
df = pd.read_csv('../data/tow-ids-dataset/raw/pkt_train.csv')

/var/folders/fs/f8qz96w55l1cqqbyb70x11380000gn/T/ipykernel_17930/2512988773.py:1: DtypeWarning: Columns (111,115,116,117,119,121,122,123,124,125,127,130,132,133,134,135,136,137,138,141,142,143,145,146,150,151,152,153,154,155,156,157,160,162,163,164,165,166,167,172,173) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('../data/tow-ids-dataset/raw/pkt_train.csv')

In [11]:
df['time_epoch_delay'] = df['frame.time_epoch'].diff().fillna(0)

In [6]:
df['is_avtp'] = df['frame.protocols'].apply(lambda x: 'ieee1722' in x)
df = df[df['is_avtp'] == True]
df.drop(columns=['is_avtp'], inplace=True)

In [ ]:
# GROUP 1: PTP
eth:ethertype:ptp


# GROUP 2: AVTP
eth:ethertype:vlan:ethertype:ieee1722:iec61883:mp2t:mp2t:mpeg-pes
eth:ethertype:vlan:ethertype:ieee1722:iec61883:mp2t:mpeg-pes:mp2t:mpeg-pes
eth:ethertype:vlan:ethertype:ieee1722:iec61883:mp2t:mpeg_sect:mpeg_pat:mp2t:mpeg_sect:mpeg_pmt
eth:ethertype:vlan:ethertype:ieee1722:iec61883:mp2t:mpeg-pes:h264:mp2t:mpeg-pes
eth:ethertype:vlan:ethertype:ieee1722:iec61883:mp2t:mp2t:mpeg-pes:h264
eth:ethertype:vlan:ethertype:ieee1722:iec61883:mp2t:mpeg-pes:mp2t:mpeg_sect:mpeg_pat
eth:ethertype:vlan:ethertype:ieee1722:iec61883:mp2t:mpeg_sect:mpeg_pmt:mp2t
eth:ethertype:vlan:ethertype:ieee1722:iec61883:mp2t:mpeg-pes:mp2t
eth:ethertype:vlan:ethertype:ieee1722:iec61883:mp2t:mpeg-pes:h264:mp2t:mpeg_sect:mpeg_pat
eth:ethertype:vlan:ethertype:ieee1722:iec61883:mp2t:mpeg-pes:h264:mp2t
eth:ethertype:vlan:ethertype:ieee1722:iec61883:mp2t:mpeg-pes:h264
eth:ethertype:vlan:ethertype:ieee1722:iec61883:mp2t:mpeg_sect:mpeg_pmt:mp2t:data
eth:ethertype:vlan:ethertype:ieee1722:iec61883:mp2t:data:mp2t
eth:ethertype:vlan:ethertype:ieee1722:iec61883:mp2t:mpeg_sect:mpeg_pmt:mp2t:mpeg-pes:h264
eth:ethertype:vlan:ethertype:ieee1722:iec61883:mp2t:mpeg-pes:mp2t:data
eth:ethertype:vlan:ethertype:ieee1722:iec61883:mp2t:mpeg-pes:mp2t:mpeg-pes:h264
eth:ethertype:vlan:ethertype:ieee1722:iec61883:mp2t:mp2t
eth:ethertype:ieee1722:ieee17221


eth:ethertype:arp

eth:ethertype:ip
eth:ethertype:ipv6:icmpv6
eth:ethertype:ip:udp:data
eth:ethertype:ip:udp:dhcp 
eth:ethertype:ip:udp:mdns
eth:ethertype:ipv6:udp:mdns 

 
eth:ethertype:mrp-mvrp
eth:ethertype:mrp-msrp

In [13]:
df['label'].value_counts()

label
Normal                 954912
CAN DoS                 85466
PTP Sync                64635
Frame Injection         35112
Switch MAC Flooding     33765
CAN Replay              29847
Name: count, dtype: int64

In [17]:
df[df['label'] == 'CAN DoS'].groupby('frame.protocols')['frame.protocols'].unique()

frame.protocols
eth:ethertype:ip:udp:data    [eth:ethertype:ip:udp:data]
Name: frame.protocols, dtype: object

In [12]:
df['frame.protocols'].unique()

array(['eth:ethertype:vlan:ethertype:ieee1722:iec61883:mp2t:mp2t',
       'eth:ethertype:ptp',
       'eth:ethertype:vlan:ethertype:ieee1722:iec61883:mp2t:mp2t:mpeg-pes',
       'eth:ethertype:vlan:ethertype:ieee1722:iec61883:mp2t:mpeg-pes:mp2t:mpeg-pes',
       'eth:ethertype:vlan:ethertype:ieee1722:iec61883:mp2t:mpeg_sect:mpeg_pat:mp2t:mpeg_sect:mpeg_pmt',
       'eth:ethertype:vlan:ethertype:ieee1722:iec61883:mp2t:mpeg-pes:h264:mp2t:mpeg-pes',
       'eth:ethertype:ip:udp:data',
       'eth:ethertype:vlan:ethertype:ieee1722:iec61883:mp2t:mp2t:mpeg-pes:h264',
       'eth:ethertype:vlan:ethertype:ieee1722:iec61883:mp2t:mpeg-pes:mp2t:mpeg_sect:mpeg_pat',
       'eth:ethertype:vlan:ethertype:ieee1722:iec61883:mp2t:mpeg_sect:mpeg_pmt:mp2t',
       'eth:ethertype:vlan:ethertype:ieee1722:iec61883:mp2t:mpeg-pes:mp2t',
       'eth:ethertype:arp', 'eth:ethertype:mrp-mvrp',
       'eth:ethertype:mrp-msrp', 'eth:ethertype:ieee1722:ieee17221',
       'eth:ethertype:ip:udp:dhcp', 'eth:ethertype:ipv6:icmpv6',
       'eth:ethertype:ip',
       'eth:ethertype:vlan:ethertype:ieee1722:iec61883:mp2t:mpeg-pes:h264:mp2t:mpeg_sect:mpeg_pat',
       'eth:ethertype:vlan:ethertype:ieee1722:iec61883:mp2t:mpeg-pes:h264:mp2t',
       'eth:ethertype:vlan:ethertype:ieee1722:iec61883:mp2t:mpeg-pes:h264',
       'eth:ethertype:vlan:ethertype:ieee1722:iec61883:mp2t:mpeg_sect:mpeg_pmt:mp2t:data',
       'eth:ethertype:vlan:ethertype:ieee1722:iec61883:mp2t:data:mp2t',
       'eth:ethertype:vlan:ethertype:ieee1722:iec61883:mp2t:mpeg_sect:mpeg_pmt:mp2t:mpeg-pes:h264',
       'eth:ethertype:vlan:ethertype:ieee1722:iec61883:mp2t:mpeg-pes:mp2t:data',
       'eth:ethertype:vlan:ethertype:ieee1722:iec61883:mp2t:mpeg-pes:mp2t:mpeg-pes:h264',
       'eth:ethertype:ipv6:udp:mdns', 'eth:ethertype:ip:udp:mdns'],
      dtype=object)

# Clean columns

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 287087 entries, 0 to 1203715
Columns: 178 entries, frame.encap_type to time_epoch_delay
dtypes: float64(80), int64(7), object(91)
memory usage: 392.1+ MB

In [8]:
df = df.dropna(thresh=0.7*len(df), axis=1)

In [9]:
def hex_to_decimal(val):
    """Convert hex string (like '0x2d91e8b7') to decimal. 
    Leave untouched if not hex or if None."""
    if isinstance(val, str) and val.startswith("0x"):
        return int(val, 16)
    return val

for col in df.columns:
    df[col] = df[col].apply(hex_to_decimal)

In [10]:
df['class'] = df['class'].apply(lambda x: 0 if x == 'Normal' else 1)

In [11]:
df.describe()

,frame.encap_type,frame.time_epoch,frame.offset_shift,frame.time_delta,frame.time_delta_displayed,frame.time_relative,frame.number,frame.len,frame.cap_len,frame.marked,...,iec61883.qpc,iec61883.sph,iec61883.dbc,iec61883.qi2,iec61883.fmt,iec61883.fdf_no_syt,iec61883.fdf_tsf,index,class,time_epoch_delay
count,287087.0,2.870870e+05,287087.0,287087.000000,287087.000000,287087.000000,2.870870e+05,287087.000000,287087.000000,287087.0,...,287013.0,287013.0,287013.000000,287013.0,287013.0,287013.0,287013.0,2.870870e+05,287087.000000,287087.000000
mean,1.0,1.599905e+09,0.0,0.000159,0.000159,290.863089,6.242756e+05,433.908599,433.908599,0.0,...,0.0,1.0,119.583712,2.0,32.0,0.0,0.0,6.242756e+05,0.122304,0.000159
std,0.0,1.546691e+02,0.0,0.000303,0.000303,154.669099,3.338000e+05,5.661966,5.661966,0.0,...,0.0,0.0,73.934840,0.0,0.0,0.0,0.0,3.338000e+05,0.327638,0.000303
min,1.0,1.599904e+09,0.0,0.000000,0.000000,0.000000,1.000000e+00,82.000000,82.000000,0.0,...,0.0,1.0,0.000000,2.0,32.0,0.0,0.0,1.000000e+00,0.000000,0.000000
25%,1.0,1.599904e+09,0.0,0.000107,0.000107,157.356263,3.537745e+05,434.000000,434.000000,0.0,...,0.0,1.0,48.000000,2.0,32.0,0.0,0.0,3.537745e+05,0.000000,0.000107
50%,1.0,1.599905e+09,0.0,0.000123,0.000123,314.644865,6.855850e+05,434.000000,434.000000,0.0,...,0.0,1.0,112.000000,2.0,32.0,0.0,0.0,6.855850e+05,0.000000,0.000123
75%,1.0,1.599905e+09,0.0,0.000126,0.000126,414.465532,8.877450e+05,434.000000,434.000000,0.0,...,0.0,1.0,176.000000,2.0,32.0,0.0,0.0,8.877450e+05,0.000000,0.000126
max,1.0,1.599905e+09,0.0,0.015079,0.015079,552.184499,1.203716e+06,434.000000,434.000000,0.0,...,0.0,1.0,240.000000,2.0,32.0,0.0,0.0,1.203716e+06,1.000000,0.015079

In [12]:
columns = df.describe().to_dict()
remove_columns = [k for k in columns.keys() if columns[k]['std'] == 0]

In [13]:
df.drop(columns=remove_columns, inplace=True)

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 287087 entries, 0 to 1203715
Data columns (total 23 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   frame.time                  287087 non-null  object
 1   frame.time_utc              287087 non-null  object
 2   frame.time_epoch            287087 non-null  float64
 3   frame.time_delta            287087 non-null  float64
 4   frame.time_delta_displayed  287087 non-null  float64
 5   frame.time_relative         287087 non-null  float64
 6   frame.number                287087 non-null  int64
 7   frame.len                   287087 non-null  int64
 8   frame.cap_len               287087 non-null  int64
 9   frame.protocols             287087 non-null  object
 10  eth.dst                     287087 non-null  object
 11  eth.src                     287087 non-null  object
 12  eth.type                    287087 non-null  int64
 13  ieee1722.subtype            287087 non-null  int64
 14  ieee1722.svfield            287087 non-null  float64
 15  iec61883.seqnum             287013 non-null  float64
 16  iec61883.stream_id          287013 non-null  float64
 17  iec61883.stream_data_len    287013 non-null  float64
 18  iec61883.dbc                287013 non-null  float64
 19  index                       287087 non-null  int64
 20  class                       287087 non-null  int64
 21  label                       287087 non-null  object
 22  time_epoch_delay            287087 non-null  float64
dtypes: float64(10), int64(7), object(6)
memory usage: 52.6+ MB

In [15]:
df.drop(columns=['frame.time', 'frame.time_utc'], inplace=True)

In [16]:
df = df.fillna(0)

In [17]:
def get_highly_correlated_features(correlation_matrix, threshold):
  correlated_pairs = []
  for i in range(len(correlation_matrix.columns)):
    for j in range(i):
      if abs(correlation_matrix.iloc[i, j]) > threshold:
        pair = (correlation_matrix.columns[i], correlation_matrix.columns[j])
        coefficient = correlation_matrix.iloc[i, j]
        correlated_pairs.append((pair, coefficient))
  return sorted(correlated_pairs, key= lambda pair: pair[1], reverse=True)

In [18]:
corr_matrix = df.drop(columns=['frame.protocols', 'eth.dst', 'eth.src', 'eth.type', 'label']).corr().abs()
correlation_list = get_highly_correlated_features(corr_matrix, 0.8)

In [19]:
correlation_list

[(('frame.time_relative', 'frame.time_epoch'), np.float64(1.0000000000000455)),
 (('iec61883.stream_id', 'ieee1722.subtype'), np.float64(1.000000000000031)),
 (('ieee1722.svfield', 'ieee1722.subtype'), np.float64(1.0000000000000244)),
 (('frame.time_delta_displayed', 'frame.time_delta'), np.float64(1.0)),
 (('frame.cap_len', 'frame.len'), np.float64(1.0)),
 (('index', 'frame.number'), np.float64(1.0)),
 (('iec61883.stream_id', 'ieee1722.svfield'), np.float64(0.9999999999999991)),
 (('time_epoch_delay', 'frame.time_delta'), np.float64(0.9999999486427514)),
 (('time_epoch_delay', 'frame.time_delta_displayed'),
  np.float64(0.9999999486427514)),
 (('iec61883.stream_data_len', 'frame.len'), np.float64(0.9999792139348257)),
 (('iec61883.stream_data_len', 'frame.cap_len'),
  np.float64(0.9999792139348257)),
 (('frame.number', 'frame.time_relative'), np.float64(0.9994552385279166)),
 (('index', 'frame.time_relative'), np.float64(0.9994552385279166)),
 (('frame.number', 'frame.time_epoch'), np.float64(0.9994552379545221)),
 (('index', 'frame.time_epoch'), np.float64(0.9994552379545221)),
 (('iec61883.stream_data_len', 'ieee1722.svfield'),
  np.float64(0.9983825685690288)),
 (('iec61883.stream_data_len', 'iec61883.stream_id'),
  np.float64(0.9983825685690232)),
 (('iec61883.stream_data_len', 'ieee1722.subtype'),
  np.float64(0.9983825685690182)),
 (('ieee1722.subtype', 'frame.len'), np.float64(0.9979952510029014)),
 (('ieee1722.subtype', 'frame.cap_len'), np.float64(0.9979952510029014)),
 (('iec61883.stream_id', 'frame.len'), np.float64(0.9979952510028998)),
 (('iec61883.stream_id', 'frame.cap_len'), np.float64(0.9979952510028998)),
 (('ieee1722.svfield', 'frame.len'), np.float64(0.9979952510028749)),
 (('ieee1722.svfield', 'frame.cap_len'), np.float64(0.9979952510028749))]

In [20]:
df.head()

,frame.time_epoch,frame.time_delta,frame.time_delta_displayed,frame.time_relative,frame.number,frame.len,frame.cap_len,frame.protocols,eth.dst,eth.src,...,ieee1722.subtype,ieee1722.svfield,iec61883.seqnum,iec61883.stream_id,iec61883.stream_data_len,iec61883.dbc,index,class,label,time_epoch_delay
0,1.599904e+09,0.000000,0.000000,0.000000,1,434,434,eth:ethertype:vlan:ethertype:ieee1722:iec61883...,91:ef:00:00:fe:00,00:fc:70:00:00:03,...,0,1.0,22.0,8.198553e+16,392.0,96.0,1,0,Normal,0.000000
1,1.599904e+09,0.000024,0.000024,0.000024,2,434,434,eth:ethertype:vlan:ethertype:ieee1722:iec61883...,91:ef:00:00:fe:00,00:fc:70:00:00:03,...,0,1.0,23.0,8.198553e+16,392.0,112.0,2,0,Normal,0.000024
2,1.599904e+09,0.000081,0.000081,0.000105,3,434,434,eth:ethertype:vlan:ethertype:ieee1722:iec61883...,91:ef:00:00:fe:00,00:fc:70:00:00:03,...,0,1.0,24.0,8.198553e+16,392.0,128.0,3,0,Normal,0.000081
3,1.599904e+09,0.000124,0.000124,0.000229,4,434,434,eth:ethertype:vlan:ethertype:ieee1722:iec61883...,91:ef:00:00:fe:00,00:fc:70:00:00:03,...,0,1.0,25.0,8.198553e+16,392.0,144.0,4,0,Normal,0.000124
4,1.599904e+09,0.000109,0.000109,0.000338,5,434,434,eth:ethertype:vlan:ethertype:ieee1722:iec61883...,91:ef:00:00:fe:00,00:fc:70:00:00:03,...,0,1.0,26.0,8.198553e+16,392.0,160.0,5,0,Normal,0.000109

In [21]:
df.drop(columns=['frame.time_relative', 'frame.time_delta_displayed', 'ieee1722.subtype', 'ieee1722.svfield', 
                 'frame.cap_len', 'index', 'time_epoch_delay', 'iec61883.stream_data_len', 'iec61883.stream_id'], inplace=True)

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 287087 entries, 0 to 1203715
Data columns (total 12 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   frame.time_epoch  287087 non-null  float64
 1   frame.time_delta  287087 non-null  float64
 2   frame.number      287087 non-null  int64
 3   frame.len         287087 non-null  int64
 4   frame.protocols   287087 non-null  object
 5   eth.dst           287087 non-null  object
 6   eth.src           287087 non-null  object
 7   eth.type          287087 non-null  int64
 8   iec61883.seqnum   287087 non-null  float64
 9   iec61883.dbc      287087 non-null  float64
 10  class             287087 non-null  int64
 11  label             287087 non-null  object
dtypes: float64(4), int64(4), object(4)
memory usage: 28.5+ MB

In [23]:
df['frame.protocols'] = df['frame.protocols'].astype('category')
df['eth.dst'] = df['eth.dst'].astype('category')
df['eth.src'] = df['eth.src'].astype('category')

In [24]:
df['frame.protocols_cat'] = df['frame.protocols'].cat.codes
df['eth.dst_cat'] = df['eth.dst'].cat.codes
df['eth.src_cat'] = df['eth.src'].cat.codes

In [25]:
df.drop(columns=['frame.protocols_cat', 'eth.dst_cat', 'eth.src_cat'], inplace=True)

In [26]:
df.head()

,frame.time_epoch,frame.time_delta,frame.number,frame.len,frame.protocols,eth.dst,eth.src,eth.type,iec61883.seqnum,iec61883.dbc,class,label
0,1.599904e+09,0.000000,1,434,eth:ethertype:vlan:ethertype:ieee1722:iec61883...,91:ef:00:00:fe:00,00:fc:70:00:00:03,33024,22.0,96.0,0,Normal
1,1.599904e+09,0.000024,2,434,eth:ethertype:vlan:ethertype:ieee1722:iec61883...,91:ef:00:00:fe:00,00:fc:70:00:00:03,33024,23.0,112.0,0,Normal
2,1.599904e+09,0.000081,3,434,eth:ethertype:vlan:ethertype:ieee1722:iec61883...,91:ef:00:00:fe:00,00:fc:70:00:00:03,33024,24.0,128.0,0,Normal
3,1.599904e+09,0.000124,4,434,eth:ethertype:vlan:ethertype:ieee1722:iec61883...,91:ef:00:00:fe:00,00:fc:70:00:00:03,33024,25.0,144.0,0,Normal
4,1.599904e+09,0.000109,5,434,eth:ethertype:vlan:ethertype:ieee1722:iec61883...,91:ef:00:00:fe:00,00:fc:70:00:00:03,33024,26.0,160.0,0,Normal

In [27]:
df['frame.time_delta']  = (df['frame.time_delta'] - df['frame.time_delta'].min()) / (df['frame.time_delta'].max() - df['frame.time_delta'].min())
df['frame.len']         = (df['frame.len'] - df['frame.len'].min()) / (df['frame.len'].max() - df['frame.len'].min())
df['eth.type']          = (df['eth.type'] - df['eth.type'].min()) / (df['eth.type'].max() - df['eth.type'].min())
df['iec61883.dbc']      = (df['iec61883.dbc'] - df['iec61883.dbc'].min()) / (df['iec61883.dbc'].max() - df['iec61883.dbc'].min())
df['iec61883.seqnum']   = (df['iec61883.seqnum'] - df['iec61883.seqnum'].min()) / (df['iec61883.seqnum'].max() - df['iec61883.seqnum'].min())

In [28]:
df.to_csv('../data/tow-ids-dataset/raw/avtp_pre_processed.csv', index=False)